import { UserRole } from '@as-finance/shared';
import type { ChapterContent } from './_types';

export const dataImportExport: ChapterContent = {
  id: 'data-import-export',
  meta: { lastReviewed: '2026-06-08', reviewedBy: 'help-maintainer', appVersion: '1.0.0' },
  langs: {
    en: {
      title: 'Data Import / Export',
      intro:
        'Move data in and out of AS-Finance as Excel files. Useful for month-end reporting, regulator submissions, and onboarding a new branch by importing a known-good config.',
      whoCanDoThis: [UserRole.SUPER_ADMIN, UserRole.MANAGER, UserRole.ACCOUNTANT, UserRole.VIEWER_AUDITOR],
      sections: [
        {
          id: 'what-you-can-do',
          heading: 'What you can export and import',
          body:
            'You can EXPORT to Excel from the Customers, Loans, Loan Products, Collections, Groups, Settings, and Holiday Calendar pages — the button is next to the "New" button on each list. You can IMPORT into Holidays, System Settings, and Loan Products via a "Import …" button on the same row. Receipts, Cashbook entries, Audit Logs, and Notifications are export-only.',
        },
        {
          id: 'exporting',
          heading: 'Exporting a list to Excel',
          body:
            'Click "Excel" near the top-right of any list page. The file downloads instantly with whatever filter is currently applied — so if you\'re looking at "Active customers in Mumbai", that\'s exactly what you get.',
          tip:
            'You can run at most 5 exports per minute. If you see "Too many exports", wait 60 seconds and try again — the limit is to protect the server.',
        },
        {
          id: 'aadhaar-mask',
          heading: 'Aadhaar in exports — masked by default',
          body:
            'For privacy and compliance, Aadhaar and mobile numbers are exported in masked form (XXXX XXXX 1234). Super Admins can choose to include FULL Aadhaar — but the override is recorded in the Audit Log with the timestamp and the actor.',
          reassure:
            'You don\'t need to remember to redact spreadsheets before sharing — the default is safe. The unmask option exists only for narrow regulatory submissions that require full IDs.',
        },
        {
          id: 'importing-holidays',
          heading: 'Importing the holiday calendar',
          body: 'Annual ritual — instead of clicking "Add Holiday" 14 times, do it in one upload.',
          steps: [
            { text: 'Sidebar → Settings → click "Import Holidays".' },
            { text: 'In the modal, click "Download blank template" — opens an .xlsx with one column "Date".' },
            { text: 'Fill the dates (YYYY-MM-DD format) — one per row. Delete the example row.' },
            { text: 'Drag the file back into the modal (or click "Choose .xlsx or .csv").' },
            { text: 'You see a preview: "✅ 14 valid, ⚠ 0 invalid". If any dates are bad, the row number + reason is listed.' },
            { text: 'Click "Import 14 valid rows". Done — the Holiday Calendar table updates.' },
          ],
          example: {
            title: 'Holiday import template',
            body: 'Column A header: Date\nRow 2:  2027-01-26\nRow 3:  2027-08-15\nRow 4:  2027-10-02\n(continue for all holidays)',
          },
        },
        {
          id: 'importing-settings',
          heading: 'Importing system settings and loan products',
          body:
            'Same flow as holidays: download template → fill values → upload → preview → commit. Settings import requires existing keys (you cannot create a new setting via Excel — that needs a code change). Loan Products import creates new products; it does NOT modify existing ones (modifying live rates would silently change EMIs on in-flight loans).',
        },
        {
          id: 'cant-import',
          heading: 'What you cannot import — and why',
          body:
            'Loans, Collections, Receipts, Customers, Users, Cashbook entries, Notifications, and Audit Logs cannot be imported from Excel. Each has a specific reason:',
          steps: [
            { text: '**Loans** — the lifecycle (draft → approval → disbursement) involves underwriting decisions. Bulk-creating loans would bypass that gate.' },
            { text: '**Collections** — money-touching. Bulk import risks double-posting; the existing safe-retry mechanism protects single-row entry.' },
            { text: '**Receipts** — auto-generated from collections; never edited by hand.' },
            { text: '**Customers** — KYC verification is per-person. Bulk import is technically possible but needs a re-verification workflow (planned V2).' },
            { text: '**Users** — bulk staff creation needs a forced password reset flow (planned V2).' },
            { text: '**Cashbook entries, Notifications, Audit Logs** — append-only or system-generated by design.' },
          ],
        },
        {
          id: 'duplicate-warning',
          heading: 'The "duplicate file" amber banner',
          body:
            'If the same file (byte-for-byte identical) was imported in the last 24 hours, you\'ll see an amber banner naming the previous import. Continue only if intentional — usually it means someone else already did this work, or you\'re about to apply the same data twice.',
        },
        {
          id: 'errors',
          heading: 'Common errors',
          body:
            '• "File too large" — limit is 5 MB. Split into multiple files.\n• "Workbook has X data rows — limit is 5000" — same. Split.\n• "Missing required columns: date" — the header row doesn\'t match the template. Re-download the template.\n• "Row 12, date: Invalid date — use YYYY-MM-DD" — fix the cell and re-upload.\n• "You do not have permission" — only Super Admin can import.',
        },
      ],
    },
    hi: {
      title: 'डेटा आयात / निर्यात',
      intro:
        'AS-Finance में डेटा को Excel फ़ाइल के रूप में अंदर-बाहर करें। महीना समापन रिपोर्ट, नियामक सबमिशन, और नई ब्रांच के सेटअप के लिए उपयोगी।',
      whoCanDoThis: [UserRole.SUPER_ADMIN, UserRole.MANAGER, UserRole.ACCOUNTANT, UserRole.VIEWER_AUDITOR],
      sections: [
        {
          id: 'what-you-can-do',
          heading: 'क्या एक्सपोर्ट और इम्पोर्ट कर सकते हैं',
          body:
            'EXPORT — Customers, Loans, Loan Products, Collections, Groups, Settings, और Holiday Calendar पेजों से। बटन "New" बटन के पास होता है। IMPORT — Holidays, System Settings, और Loan Products में, "Import …" बटन से। Receipts, Cashbook entries, Audit Logs, और Notifications सिर्फ़ एक्सपोर्ट होते हैं।',
        },
        {
          id: 'exporting',
          heading: 'सूची को Excel में एक्सपोर्ट',
          body:
            'किसी भी सूची पेज पर ऊपर-दाएँ "Excel" दबाएँ। फ़ाइल तुरंत डाउनलोड होती है — जो फ़िल्टर लागू है वही डेटा निकलेगा। यानी "Active customers in Mumbai" देखते हैं तो वही मिलेगा।',
          tip: 'अधिकतम 5 एक्सपोर्ट प्रति मिनट। "Too many exports" दिखे तो 60 सेकंड रुकें — सर्वर की सुरक्षा के लिए।',
        },
        {
          id: 'aadhaar-mask',
          heading: 'एक्सपोर्ट में आधार — डिफ़ॉल्ट से छुपा',
          body:
            'गोपनीयता के लिए आधार और मोबाइल नंबर छुपे रूप (XXXX XXXX 1234) में जाते हैं। सिर्फ़ Super Admin पूरा आधार शामिल कर सकता है — पर यह निर्णय ऑडिट लॉग में समय और कर्ता के साथ दर्ज होता है।',
          reassure: 'साझा करने से पहले स्प्रेडशीट साफ़ करना याद रखने की ज़रूरत नहीं — डिफ़ॉल्ट सुरक्षित है। अनमास्क सिर्फ़ ख़ास नियामक माँग के लिए।',
        },
        {
          id: 'importing-holidays',
          heading: 'छुट्टी कैलेंडर इम्पोर्ट',
          body: 'सालाना रस्म — "Add Holiday" 14 बार दबाने की जगह, एक ही अपलोड में।',
          steps: [
            { text: 'साइडबार → Settings → "Import Holidays" दबाएँ।' },
            { text: 'मॉडल में "Download blank template" दबाएँ — एक कॉलम "Date" वाली .xlsx खुलेगी।' },
            { text: 'तारीख़ें भरें (YYYY-MM-DD प्रारूप) — हर पंक्ति में एक। उदाहरण पंक्ति हटाएँ।' },
            { text: 'फ़ाइल को वापस मॉडल में खींचें (या "Choose .xlsx or .csv" क्लिक करें)।' },
            { text: 'प्रिव्यू दिखेगा: "✅ 14 valid, ⚠ 0 invalid"। ग़लत तारीख़ हो तो पंक्ति नंबर + कारण दिखेगा।' },
            { text: '"Import 14 valid rows" दबाएँ। हो गया — Holiday Calendar अपडेट हो जाएगा।' },
          ],
          example: {
            title: 'छुट्टी इम्पोर्ट टेम्पलेट',
            body: 'A1: Date\nA2: 2027-01-26\nA3: 2027-08-15\nA4: 2027-10-02\n(हर छुट्टी के लिए)',
          },
        },
        {
          id: 'importing-settings',
          heading: 'सिस्टम सेटिंग्स और लोन प्रोडक्ट्स इम्पोर्ट',
          body:
            'छुट्टी जैसा ही फ़्लो: टेम्पलेट डाउनलोड → भरें → अपलोड → प्रिव्यू → कमिट। सेटिंग्स इम्पोर्ट के लिए key पहले से मौजूद होनी चाहिए (नई key Excel से नहीं बनती)। Loan Products इम्पोर्ट नए प्रोडक्ट बनाता है; मौजूदा को नहीं बदलता (चालू दर बदलना EMIs को चुपचाप बदल देता)।',
        },
        {
          id: 'cant-import',
          heading: 'क्या इम्पोर्ट नहीं हो सकता — और क्यों',
          body: 'Loans, Collections, Receipts, Customers, Users, Cashbook, Notifications, और Audit Logs Excel से इम्पोर्ट नहीं हो सकते।',
          steps: [
            { text: '**Loans** — जीवन-चक्र (draft → अप्रूव → वितरण) में अंडरराइटिंग निर्णय होते हैं। बल्क बनाना उस गेट को छोड़ देगा।' },
            { text: '**Collections** — पैसा छूता है। बल्क इम्पोर्ट दो बार पोस्ट होने का जोखिम।' },
            { text: '**Receipts** — कलेक्शन से अपने आप बनती हैं।' },
            { text: '**Customers** — KYC प्रति-व्यक्ति। बल्क संभव है पर पुनः-सत्यापन वर्कफ़्लो चाहिए (V2 में)।' },
            { text: '**Users** — पासवर्ड रीसेट फ़्लो चाहिए (V2 में)।' },
            { text: '**Cashbook, Notifications, Audit Logs** — डिज़ाइन से append-only/सिस्टम-जनित।' },
          ],
        },
        {
          id: 'duplicate-warning',
          heading: 'डुप्लिकेट फ़ाइल चेतावनी',
          body:
            'अगर वही फ़ाइल पिछले 24 घंटों में इम्पोर्ट हुई हो (बाइट-बाइट एक जैसी), तो अंबर बैनर दिखेगा। जान-बूझकर ही जारी रखें — आमतौर पर मतलब कोई और पहले कर चुका है।',
        },
        {
          id: 'errors',
          heading: 'आम गलतियाँ',
          body:
            '• "File too large" — 5 MB तक। बाँट लें।\n• "5000 rows" से ज़्यादा — बाँट लें।\n• "Missing required columns" — हेडर मेल नहीं। टेम्पलेट फिर से।\n• "Row X, date: Invalid date — use YYYY-MM-DD" — सेल ठीक करें।\n• "You do not have permission" — सिर्फ़ Super Admin इम्पोर्ट कर सकता है।',
        },
      ],
    },
    hinglish: {
      title: 'Data Import / Export',
      intro:
        'AS-Finance mein data Excel files ke roop mein andar-bahar lao. Month-end reports, regulator submissions, aur nayi branch onboarding ke liye useful.',
      whoCanDoThis: [UserRole.SUPER_ADMIN, UserRole.MANAGER, UserRole.ACCOUNTANT, UserRole.VIEWER_AUDITOR],
      sections: [
        {
          id: 'what-you-can-do',
          heading: 'Kya export aur import kar sakte ho',
          body:
            'EXPORT — Customers, Loans, Loan Products, Collections, Groups, Settings, aur Holiday Calendar pages se. Button "New" button ke paas hota hai. IMPORT — Holidays, System Settings, aur Loan Products mein, "Import …" button se. Receipts, Cashbook entries, Audit Logs, aur Notifications sirf export-only.',
        },
        {
          id: 'exporting',
          heading: 'List ko Excel mein export',
          body:
            'Kisi bhi list page par top-right "Excel" dabao. File turant download hoti hai — jo filter applied hai wahi data niklega. Yani "Active customers in Mumbai" dekh rahe ho to wahi milega.',
          tip: 'Max 5 exports per minute. "Too many exports" dikhe to 60 second ruko — server protection ke liye.',
        },
        {
          id: 'aadhaar-mask',
          heading: 'Export mein Aadhaar — default se masked',
          body:
            'Privacy ke liye Aadhaar aur mobile numbers masked (XXXX XXXX 1234) mein jaate hain. Sirf Super Admin full Aadhaar include kar sakta hai — par decision Audit Log mein timestamp + actor ke saath record hota hai.',
          reassure:
            'Share karne se pehle spreadsheet redact karne ki tension nahi — default safe hai. Unmask option sirf specific regulatory submissions ke liye.',
        },
        {
          id: 'importing-holidays',
          heading: 'Holiday calendar import',
          body: 'Saalana ritual — "Add Holiday" 14 baar dabane ki jagah, ek hi upload mein.',
          steps: [
            { text: 'Sidebar → Settings → "Import Holidays" dabao.' },
            { text: 'Modal mein "Download blank template" dabao — ek column "Date" wali .xlsx khulegi.' },
            { text: 'Dates fill karo (YYYY-MM-DD format) — har row mein ek. Example row delete karo.' },
            { text: 'File ko wapas modal mein drag karo (ya "Choose .xlsx or .csv" click).' },
            { text: 'Preview dikhega: "✅ 14 valid, ⚠ 0 invalid". Galat dates ho to row number + reason listed.' },
            { text: '"Import 14 valid rows" dabao. Done — Holiday Calendar update ho jaayega.' },
          ],
          example: {
            title: 'Holiday import template',
            body: 'A1: Date\nA2: 2027-01-26\nA3: 2027-08-15\nA4: 2027-10-02\n(har holiday ke liye)',
          },
        },
        {
          id: 'importing-settings',
          heading: 'System settings aur loan products import',
          body:
            'Holidays jaisa hi flow: template download → fill karo → upload → preview → commit. Settings import ke liye key already exist karni chahiye (nayi key Excel se nahi banti). Loan Products import naye products banata hai; existing modify NAHI karta (live rates badalna in-flight loans ki EMIs ko silently badal dega).',
        },
        {
          id: 'cant-import',
          heading: 'Kya import nahi ho sakta — aur kyun',
          body: 'Loans, Collections, Receipts, Customers, Users, Cashbook, Notifications, aur Audit Logs Excel se import nahi ho sakte.',
          steps: [
            { text: '**Loans** — lifecycle (draft → approval → disbursement) mein underwriting decisions hote hain. Bulk banane se wo gate bypass ho jaayega.' },
            { text: '**Collections** — money touch hota hai. Bulk import double-post ka risk.' },
            { text: '**Receipts** — collections se auto-generated; hand se edit nahi.' },
            { text: '**Customers** — KYC per-person. Bulk possible hai par re-verification workflow chahiye (V2 mein planned).' },
            { text: '**Users** — password reset flow chahiye (V2 mein planned).' },
            { text: '**Cashbook, Notifications, Audit Logs** — design se append-only/system-generated.' },
          ],
        },
        {
          id: 'duplicate-warning',
          heading: '"Duplicate file" amber banner',
          body:
            'Agar same file (byte-byte identical) last 24 hours mein import hui ho, amber banner dikhega previous import name ke saath. Intentional ho tabhi continue karo — usually matlab kisi ne pehle hi yeh kaam kiya hai, ya same data 2 baar apply hone wala hai.',
        },
        {
          id: 'errors',
          heading: 'Common errors',
          body:
            '• "File too large" — limit 5 MB. Split kar lo.\n• "5000 rows" se zyada — split.\n• "Missing required columns" — header row template se match nahi. Re-download.\n• "Row X, date: Invalid — use YYYY-MM-DD" — cell fix karo.\n• "You do not have permission" — sirf Super Admin import kar sakta hai.',
        },
      ],
    },
  },
};
